### ISSUE TITLE
504 errors on storeKeyPrefix

### ISSUE THREAD

**Issue by jeffggardner** [hashicorp/envconsul#133] opened 2017-03-22 15:23 UTC
I have a 3-node consul [v0.7.5] cluster in AWS behind an ELB that listens on port 80 and forwards to port 8500 and nodejs microservices that use envconsul to populate their environment.  Every minute we get HTTP 504 error as shown in the debug output below.  Why are we getting so many 504 errors and how do we prevent them?

### Envconsul version
envconsul v0.6.3 (4070d9a)

### Command
```
/usr/bin/envconsul -kill-signal SIGHUP -splay 30s -log-level debug  -consul $CONSUL_URL -sanitize -prefix authentication-service/$ENVIRONMENT node app.js  
```

### Debug output
```
2017/03/22 15:13:26 [ERR] (view) "storeKeyPrefix(authentication-service/prod1)" store key prefix: error fetching: Unexpected response code: 504
2017/03/22 15:13:26 [INFO] (view) "storeKeyPrefix(authentication-service/prod1)" errored, retrying in 5s
2017/03/22 15:13:26 [ERR] (runner) watcher reported error: store key prefix: error fetching: Unexpected response code: 504
2017/03/22 15:13:26 [INFO] (runner) running
2017/03/22 15:13:26 [DEBUG] (runner) setting MRS_EncryptionKey="<snip>" from "storeKeyPrefix(authentication-service/prod1)"
2017/03/22 15:13:26 [DEBUG] (runner) setting MRS_Endpoint="<snip>" from "storeKeyPrefix(authentication-service/prod1)"
2017/03/22 15:13:26 [DEBUG] (runner) setting MRS_Hostname="<snip>" from "storeKeyPrefix(authentication-service/prod1)"
2017/03/22 15:13:26 [DEBUG] (runner) setting MRS_InitVector="<snip>" from "storeKeyPrefix(authentication-service/prod1)"
2017/03/22 15:13:26 [DEBUG] (runner) setting MRS_PORT="443" from "storeKeyPrefix(authentication-service/prod1)"
2017/03/22 15:13:26 [DEBUG] (runner) setting SECRET_KEY="<snip>" from "storeKeyPrefix(authentication-service/prod1)"
2017/03/22 15:13:26 [DEBUG] (runner) setting SPLUNK_INDEX="<snip>" from "storeKeyPrefix(authentication-service/prod1)"
2017/03/22 15:13:26 [DEBUG] Environment:
2017/03/22 15:13:26 [DEBUG]   MRS_Endpoint="<snip>"
2017/03/22 15:13:26 [DEBUG]   MRS_Hostname="<snip>"
2017/03/22 15:13:26 [DEBUG]   MRS_InitVector="<snip>"
2017/03/22 15:13:26 [DEBUG]   MRS_PORT="443"
2017/03/22 15:13:26 [DEBUG]   SECRET_KEY="<snip>"
2017/03/22 15:13:26 [DEBUG]   SPLUNK_INDEX="<snip>"
2017/03/22 15:13:26 [DEBUG]   MRS_EncryptionKey="<snip>"
2017/03/22 15:13:26 [INFO] (runner) environment was the same
2017/03/22 15:13:31 [DEBUG] (view) "storeKeyPrefix(authentication-service/prod1)" starting fetch
2017/03/22 15:13:31 [DEBUG] ("storeKeyPrefix(authentication-service/prod1)") querying consul with &{Datacenter: AllowStale:true RequireConsistent:false WaitIndex:596 WaitTime:1m0s Token: Near:}
```

**Comment by sethvargo** [comment] 2017-03-22 16:31
Duplicate of https://github.com/hashicorp/envconsul/issues/109

**Closed by sethvargo** 2017-03-22 16:31 UTC
