### ISSUE TITLE
Non-prefixed environment variables

### ISSUE THREAD

**Issue by xyzjace** [hashicorp/envconsul#106] opened 2016-04-29 01:52 UTC
Hi there,

I've been trying to get envconsul up and running talking to a Vault instance reading from a secret. Let's say `secret/foo` for now. 

I can read the secret, but end up with `secret_foo_whateverkey`. For my purposes, I don't want to have the `secret_foo` prefix on any of my environment variables.

I've tried the `format` option, but that doesn't seem to produce what I want.

Have I missed something, or is this not possible? If it's not possible, are there any plans to make it possible to not prefix the environment variables?

I understand the risk of clobbering existing environment variables you're trying to avoid, but for my uses it won't be a problem.

**Comment by sethvargo** [comment] 2016-04-29 16:07
Dupe of https://github.com/hashicorp/envconsul/issues/84. Let's track that instead please. Thanks! 😄

**Closed by sethvargo** 2016-04-29 16:07 UTC
