### ISSUE TITLE
using envconsul with spring's PropertyPlaceholderConfigurer

### ISSUE THREAD

**Issue by arthurtsang** [hashicorp/envconsul#89] opened 2016-02-24 23:35 UTC
i have an existing application using spring's PropertyPlaceholderConfigurer with SYSTEM_PROPERTIES_MODE_OVERRIDE.  and i have properties like these
```
database.url=...
database.username=...
database.password=...
```
currently we put the encrypted password to the config, but we'd like to use ```vault``` instead.  it'd be nice if we can use ```envconsul``` to get the database password from vault under ```secret/database/password```.  but currently it's generating an env variable, ```secret_database_password_vault```

it'd be nice if we can have ```envconsul```  to use ```.``` instead of ```_``` and a way to strip off ```secret_``` and if it's just ```value```, strip that too.

**Comment by arthurtsang** [comment] 2016-02-25 02:55
i've made the change, but i don't know golang, the code probably look terrible.  

https://github.com/arthurtsang/envconsul/tree/v0.6.1
https://github.com/arthurtsang/envconsul/releases/tag/v0.6.1

**Comment by sethvargo** [comment] 2016-04-29 16:09
Hi there. This is really a duplicate of https://github.com/hashicorp/envconsul/issues/84 with an additional ask of custom formatting. Let's track that issue instead please. Thanks! 😄

**Closed by sethvargo** 2016-04-29 16:09 UTC
