### ISSUE TITLE
v0.8.0 release bad gpg sigs

### ISSUE THREAD

**Issue by flyinprogrammer** [hashicorp/envconsul#214] opened 2019-06-11 16:44 UTC
### Envconsul version
v0.8.0

### Expected behavior
These artifacts to be properly signed by Hashicorp.

### Actual behavior
The artifacts aren't properly signed.

### Steps to reproduce
```shell
curl -OL https://releases.hashicorp.com/envconsul/0.8.0/envconsul_0.8.0_SHA256SUMS
curl -OL https://releases.hashicorp.com/envconsul/0.8.0/envconsul_0.8.0_SHA256SUMS.sig
gpg --verify envconsul_0.8.0_SHA256SUMS.sig envconsul_0.8.0_SHA256SUMS
# gpg: Signature made Mon Jun 10 17:17:47 2019 CDT
# gpg:                using RSA key 91A6E7F85D05C65630BEF18951852D87348FFC4C
# gpg: BAD signature from "HashiCorp Security <security@hashicorp.com>" [unknown]
shasum envconsul_0.8.0_SHA256SUMS.sig
# 9657cf72277377e2801a4cc0d161c9279b9bf591  envconsul_0.8.0_SHA256SUMS.sig
shasum envconsul_0.8.0_SHA256SUMS
# fa01b37d87a348f99d016f87cac031835a7168c6  envconsul_0.8.0_SHA256SUMS
```

**Comment by eikenb** [comment] 2019-06-11 18:18
@flyinprogrammer .. Hey Alan, great to hear from you (even if in a bug).

Thanks for the report, not sure what happened with the signatures but I'll get it sorted out.

**Comment by eikenb** [comment] 2019-06-11 21:56
So it seems there is a race in the Makefile, such that it is computing the signature before the previous steps have fully completed. If I just add a 1 second sleep between the compress/checksuming and the signing it gets a good signature, otherwise it is bad. 

I didn't think make could have races like that. I'm going to have to dig into that a bit.

**Comment by eikenb** [comment] 2019-06-11 23:12
The problem is the checksum file is empty when the signature is calculated. Tracked it down to a bashism in the Makefile. It used `&>` which in bash redirects both stdout and stderr, but using a POSIX shell (like dash, the default shell on most linux distros) it is just read ad `& >` ... that is, run the command in the background and redirect stdout.

TLRD; it was running the checksum calculation in the background when it shouldn't have

**Comment by eikenb** [comment] 2019-06-11 23:59
Pushed up the fix for the Makefile, waiting to close this until I've resolved the issue with the bad signature in the release. Probably going to re-push new binaries with the proper checksum/signatures but I want to check with our release engineer first.

**Comment by eikenb** [comment] 2019-06-12 20:20
Re-pushed the binaries with a valid signature on the checksum file.

**Closed by eikenb** 2019-06-12 20:20 UTC
Labels: bug
