### ISSUE TITLE
envconsul stops after one execution of the command

### ISSUE THREAD

**Issue by kaelumania** [hashicorp/envconsul#44] opened 2015-04-24 14:17 UTC
`envconsul -log-level debug -prefix env/loadbalancer env`

**Comment by sethvargo** [comment] 2015-04-24 15:17
Hi @kaelumania 

This is the expected behavior for commands that exit. Since the `env` command exits (i.e. does not run in a daemon mode), envconsul does not have a command to monitor and restart. Does that make sense?

**Comment by kaelumania** [comment] 2015-04-25 06:58
oh really? I was expecting that whenever a key/value (`env/loadbalancer`) changes the command (`env`) is being executed. Thus, envconsul should be a daemon right? Otherwise why would there be a `-once` option?

**Comment by sethvargo** [comment] 2015-04-25 17:50
Hi @kaelumania 

envconsul is more of a process monitor. It grabs the current environment and sets everything up, then executes the command. It controls and monitors that subprocess and, if the data from consul changes, it updates the environment and tells the process to restart.

Since a command like `env` exits, envconsul has no active process to restart. I'm not sure what you mean by "envconsul should be a daemon". The `-once` flag tells envconsul to only pull down the most recent data from Consul (but not watch for changes). 

If you just want to get the values from Consul one time and start a command, you use the `-once` flag:

```shell
envconsul -consul demo.consul.io -prefix global -once /bin/sh -c "env; echo "-----"; sleep 1000"
```

This will print something like:

```
time=Sat Apr 25 13:48:49 EDT 2015
```

but if that value changes, nothing will happen. However, without the `-once` flag, the env command will be re-run if anything in the `global` namespace changes (since that is the key we are watching):

```shell
envconsul -consul demo.consul.io -prefix global /bin/sh -c "env; echo "-----"; sleep 1000"
```

now you will see output like:

```
time=Sat Apr 25 13:49:49 EDT 2015
time=Sat Apr 25 13:50:04 EDT 2015
time=Sat Apr 25 13:50:19 EDT 2015
```

each time the value changes, the `env` command is re-run.

Does that help clear things up?

**Comment by kaelumania** [comment] 2015-04-27 06:36
okay. `envconsul` is not a daemon and calls the command on every change. instead it monitors the process started by the command and sends a signal to the process when something changed?

**Comment by sethvargo** [comment] 2015-04-27 11:22
Hi @kaelumania 

It calls the command on the first change. Then, it kills/restarts the command when data in Consul changes.

**Comment by sethvargo** [comment] 2015-05-11 15:12
Hi @kaelumania 

I am going to close this issue, but please let me know if you have any additional questions of if there is anything I can help to clarify.

**Closed by sethvargo** 2015-05-11 15:12 UTC
