### ISSUE TITLE
envconsul unable to read prefixed_keys from Vault (works for singleKey)

### ISSUE THREAD

**Issue by zeeshanChegg** [hashicorp/envconsul#171] opened 2018-04-11 00:00 UTC
### Envconsul version
```
envconsul v0.7.3 (daa2947)
```

### Configuration
```hcl
consul
{
	address = "10.108.34.100:8500"
}

exec
{
	command = "env"
	env
	{
		pristine = true
	}
}

log_level = "debug"
# pid_file = "/apps/en2consul/pid"

syslog
{
  enabled=true
  facility = "LOCAL5"
}

prefix
{
	path = "config_set/test-api/prod"
}

secret
{
	no_prefix = true
	path = "secret-kv/config_set/test-api/prod/"
}

vault
{
	address = "http://10.108.35.200:8200"
}
```

### Command
```shell
export VAULT_TOKEN=$(curl -s <URL>)
envconsul -config config.hcl 
```

### Debug output
https://gist.github.com/zeeshanChegg/27f2681018ef21a41b84b85fe4ea1ed2

### Expected behavior
Retrieve all configs from vault under secret-path 'secret-kv/config_set/test-api/prod/'. 
If I change the path to 'secret-kv/config_set/test-api/prod/datasource.password' it's able to fetch the value. 

### Actual behavior
envconsul goes into a loop looking for the value saying it doesnt exist (although it does)

### Steps to reproduce
1. run envconsul -config config.hcl (change IP of servers and configs to your settings)
2. envconsul never finishes and unable to get keys under 'secret-kv/config_set/test-api/prod/'

**Comment by catsby** [comment] 2018-07-30 21:01
Hey there! I'm curious if you're still hitting this issue. I noticed this in the debug output:

```
$envconsul -config "config.hcl"

2018/04/10 16:52:04 [DEBUG] (logging) enabling syslog on LOCAL5
2018/04/10 23:52:04.372982 [INFO] (runner) creating watcher
2018/04/10 23:52:04.373074 [DEBUG] (watcher) adding vault.token
2018/04/10 23:52:04.373205 looking at vault secret-kv/config_set/test-api/prod/datasource.password
[...]
2018/04/10 23:52:04.374280 [DEBUG] (watcher) adding vault.read(secret-kv/config_set/test-api/prod/datasource.password)
[...]
2018/04/10 23:52:04.377107 [INFO] (runner) missing data for vault.read(secret-kv/config_set/test-api/prod/datasource.password)
2018/04/10 23:52:04.377297 [DEBUG] (runner) receiving dependency vault.read(secret-kv/config_set/test-api/prod/datasource.password)
[...]
2018/04/10 23:52:04.377640 [DEBUG] (runner) setting value="jjtGxsdf324fd1" from vault.read(secret-kv/config_set/test-api/prod/datasource.password)
2018/04/10 23:52:04.377779 [INFO] (child) spawning: env
[...]
value=jjtGxsdf324fd1
[...]
2018/04/10 23:52:04.379437 [DEBUG] (runner) setting value="jjtGxsdf324fd1" from vault.read(secret-kv/config_set/test-api/prod/datasource.password)
2018/04/10 23:52:04.379525 [INFO] (runner) environment was the same
2018/04/10 23:52:04.379115 [DEBUG] (cli) receiving signal "child exited"
2018/04/10 23:52:04.379697 [INFO] (cli) subprocess exited
2018/04/10 23:52:04.379753 [INFO] (runner) stopping
2018/04/10 23:52:04.379804 [DEBUG] (runner) stopping watcher
2018/04/10 23:52:04.379885 [DEBUG] (watcher) stopping all views
2018/04/10 23:52:04.379956 [DEBUG] (runner) stopping child process
2018/04/10 23:52:04.379995 [INFO] (child) stopping process
```

It looks like a value is read `jjtGxsdf324fd1` but not properly named in the environment (no `datasource.password`. 

Let us know if you're still hitting this issue. Thanks!

**Comment by eikenb** [comment] 2019-05-17 21:14
I just hit this myself.

(VAULT_TOKEN is set)
```
[~]vault kv put secret/hello foo=world
[~]vault kv get secret/hello
====== Metadata ======
Key              Value
---              -----
created_time     2019-05-17T21:12:00.747097583Z
deletion_time    n/a
destroyed        false
version          1

=== Data ===
Key    Value
---    -----
foo    world
[~]envconsul -secret secret/hello -pristine env
2019/05/17 21:12:57.600053 [WARN] (view) vault.read(secret/hello): no secret exists at secret/hello (retry attempt 1 after "250ms")
2019/05/17 21:12:57.852407 [WARN] (view) vault.read(secret/hello): no secret exists at secret/hello (retry attempt 2 after "500ms")
...

```

**Comment by eikenb** [comment] 2019-05-17 22:09
My case, and I think probably yours as well @zeeshanChegg, is that I was using the V1 Vault API for the query path instead of V2. Changing my call to this worked...

(Note the additional `/data` in the path)
```
[~]envconsul -secret secret/data/hello -pristine env
secret_data_hello_foo=world
```

**Comment by eikenb** [comment] 2019-05-20 22:17
As I'm pretty sure I reproduced the original issue and figured out the problem was just a change to the prefix in V2 of vault, I'm going to close this issue as resolved.

**Closed by eikenb** 2019-05-20 22:17 UTC
Labels: bug
