### ISSUE TITLE
(configuration) path is required if secret block is present

### ISSUE THREAD

**Issue by elboletaire** [hashicorp/envconsul#165] opened 2018-02-22 14:09 UTC
### Envconsul version
0.7.3 (daa2947)

### Configuration
```hcl
consul {
  address = "consul.service.consul:8500"

  ssl {
    enabled = false
  }

  retry {
    enabled = true
    attempts = 12
    backoff = "10s"
  }
}

max_stale = "10m"

exec {
  splay = "5s"
  kill_timeout = "5s"
}

vault {
  address = "http://vault.service.consul:8200"
  renew_token = false

  ssl {
    enabled = false
  }

  retry {
    enabled = true
    attempts = 12
    backoff = "10s"
  }
}

secret {
  no_prefix = true
  format = "DB_{{ key }}"
}

```
### Command
```shell
envconsul -secret="mongodb/creds/ptv_master" -config="deploy/envconsul.hcl" node .
```

### Expected behavior
As said in your changelog.md file, since version 0.7.0 `(configuration) path is deprecated and there is no configuration file replacement. Use the CLI option instead.`.

That's not true. Not specifying a path in the config file makes envconsul crash. You **must** still set it under `secret { path = "" }` to make it work.

### Actual behavior
~~~
2018/02/22 14:03:30.660697 looking at vault
2018/02/22 14:03:30.660731 [ERR] (cli) vault.read: invalid format: ""
~~~

### Steps to reproduce
1. Create a consul config file **without the path** specified in `secret`.
2. Run envconsul specifying the proper secret via `-secret`
3. Enjoy

PS. I'm creating this issue after (accidentally) upgrading from 0.6.2 to the latest version. Even with the specified changes, envconsul is not able to connect to vault. It always returns a `renewed returned` error... That's why I'm trying to make all the changes as specified in changelog, but as stated it does not work.

PS2. Please, update the config file in the readme. It does not reflect all these changes.

**Comment by antonu17** [comment] 2019-01-23 16:25
Confirm. It is actually creates 2 secret entries:
```shell
cat ~/.envconsul.hcl 
secret {
   no_prefix = true
}
envconsul -vault-addr="${VAULT_ADDR}" -vault-token="${VAULT_TOKEN}" -config ~/.envconsul.hcl -secret "secret/test" -pristine -log-level debug env
...
"Secrets":[{"Format":"","NoPrefix":true,"Path":""},{"Format":"","NoPrefix":false,"Path":"secret/test"}],
...
```
Offtopic, is it possible to provide `no_prefix` via cmdline option?

**Comment by freddygv** [comment] 2019-04-26 18:42
The `path` referred to in the changelog was to a top-level config field called path. This path was for the configuration file, which is now set with `-config` in the CLI.

It was removed here:
https://github.com/hashicorp/envconsul/commit/52119ff4c0b39292c77aefccb98b0f3f422abf0e#diff-b4bda758a2aef091432646c354b4dc59L96

The path that was deprecated is different from `secret.path` as well as `prefix.path`

**Comment by williams-brian** [comment] 2020-03-12 20:12
@freddygv Can you explain why you closed this? Is this behavior not a bug? While @elboletaire's interpretation of the deprecation change may have been incorrect, it seems to me like the behavior occurring here is still unexpected.

If you set a `secret` block without providing a key, then it over-rides the value of the `-secret` argument with an empty string. Is this intended?

```
$ cat envconsul.hcl 
vault {
  address = "https://vault-dev.company.com"

  ssl {
    enabled = true
  }
}
$ envconsul -once -config=envconsul.hcl -secret=kv/test echo noop
2020/03/12 20:06:16.089272 [WARN] vault.token: TTL of "30m0s" exceeded the effective max_ttl of "13m36s"; TTL value is capped accordingly
noop
$ cat envconsul.hcl                                              
secret {
  no_prefix = true
}

vault {
  address = "https://vault-dev.company.com"

  ssl {
    enabled = true
  }
}
$ envconsul -once -config=envconsul.hcl -secret=kv/test echo noop
2020/03/12 20:06:39.772122 [ERR] (cli) vault.read: invalid format: ""
```

The readme says this:

```
# This specifies a secret in Vault to watch. This may be specified multiple
# times to watch multiple secrets, and the bottom-most secret takes
# precedence, should any values overlap.
secret {
  # See `prefix` as they are the same options.
}

# This specifies a prefix in Consul to watch. This may be specified multiple
# times to watch multiple prefixes, and the bottom-most prefix takes
# precedence, should any values overlap.
prefix {
  # This tells Envconsul to use a custom formatter when printing the key. The
  # value between `{{ key }}` will be replaced with the key.
  format = "custom_{{ key }}"

  # This tells Envconsul to not prefix the keys with their parent "folder".
  # The default for `prefix` (consul) is true, the default for `secret` (vault)
  # is false. The differing defaults is to maintain backward compatibility.
  no_prefix = false

  # This is the path of the key in Consul or Vault from which to read data.
  path = "foo/bar"
}
```

I suppose that is how it's supposed to work, because there can be multiple secrets, but there are two problems which make this behavior confusing.

1. There's no (documented) way to set no_prefix via the command line
2. Nowhere does it say that `secret.key` is a required attribute, but it seems that it is

**Comment by eikenb** [comment] 2020-03-13 19:28
Thanks @freddygv for re-opening this.

@williams-brian, thanks for the comment as indeed something should be done here. Though if freddy hadn't noticed this, I almost certainly wouldn't have as I don't monitor closed tickets. Please consider opening a new ticket with a reference to the old next time as that will definitely get someone's attention.

I'm going to (option A) review the code to see if `path` can be made optional and, if so, I'll go that way. Otherwise (option B) I'll look into documenting that it is required if you have a `secret` block and adding a `-noprefix` CLI option.

**Comment by eikenb** [comment] 2020-03-13 20:13
Another thing that needs addressing is the secret config block over-writing the secret command line option. That is backwards from standard/expected behavior and a bug.

**Comment by eikenb** [comment] 2020-04-13 23:29
Figured part of it out. Both prefix and secret will accept multiple entries. When you specify it on the command line that is just considered another entry, not overriding the entry in the config file. 

So when you have a `secret {}` section in the config file it adds it and initializes the `path` to "" then the `-secret` on the command line gets appended after that as another entry. Then when it goes to process things it hits the entry from the config file with `path=""` and spits out that error. Never even making it to the second `secret` entry added from processing the command line args.

**Comment by eikenb** [comment] 2020-04-14 00:46
The fix seems to be to just skip `secret` config sections without a `path` set. Having any other settings in there with no path is meaningless as there will be no secrets loaded. And this would fix the case where you had both a config section and a cli option.

Additionally I think some documentation fixes laying this out more clearly would be needed as well.

**Closed** 2020-04-25 00:14 UTC
Labels: bug, documentation
